### PR TITLE
Update iOS deployment target

### PR DESCRIPTION
**Pull request by artemisia-absynthium**
Update iOS deployment target to reflect minimum version supported by Xcode 12.

### CODE REVIEW

**Comment by stuffmc** [comment]
BUMP! ;-)

**Comment by KaneCheshire** [comment]
Sorry I will try and get to this this week :) I've had a mixture of depression (thanks to the pandemic) and a new job so I've struggled to find time for anything else, apologies!

**Comment by stuffmc** [comment]
No worries. Thanks for your time! ;)

**Comment by artemisia-absynthium** [comment]
No worries!! Thanks for your awesome work! 😃

**Review by KaneCheshire — APPROVED** [review]

**Pull request merged**
